## One time script to download data till date

In [78]:
pip install pymongo

Requirement already satisfied: pymongo in /Users/vishalranjan/opt/anaconda3/lib/python3.7/site-packages (3.10.1)
Note: you may need to restart the kernel to use updated packages.

In [79]:
import pandas as pd
import requests
import io
import datetime
import pymongo
import numpy as np

In [112]:
base_path_john_hopkins_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/'

first_available_data_date = datetime.date(2020,1,22)
today = datetime.date.today()

days_since_first_data = (today-first_available_data_date).days
date_iterator = first_available_data_date
for day in range(days_since_first_data):
    
    date_iterator_month = str(date_iterator.month) if len(str(date_iterator.month)) > 1 else '0'+str(date_iterator.month)
    date_iterator_day = str(date_iterator.day) if len(str(date_iterator.day)) > 1 else '0'+str(date_iterator.day)
    date_iterator_year = str(date_iterator.year)
    valid_file_name = date_iterator_month + '-' + date_iterator_day + '-' + date_iterator_year +'.csv'
    
    print(day," st day valid date is:",valid_file_name)
    r = requests.get(base_path_john_hopkins_url+valid_file_name)
    try:
        if r.ok:
            data = r.content.decode('utf8')
            df = pd.read_csv(io.StringIO(data))
            df.to_csv('data/'+valid_file_name,index=False)
    except:
        break 
    date_iterator = date_iterator + datetime.timedelta(days=1)
        
   


# print(today)

# d = datetime.datetime(2020,1,2)
# d.month
# d.day
# nextday = d + datetime.timedelta(days = 5) 

# print(nextday)

# print((nextday-d).days)

SyntaxError: 'return' outside function (<ipython-input-112-5a7e7ef16e8c>, line 23)

In [81]:
df

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-05-13 03:32:26,34.223334,-82.461707,34,0,0,34,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-05-13 03:32:26,30.295065,-92.414197,152,11,0,141,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-05-13 03:32:26,37.767072,-75.632346,530,7,0,523,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-05-13 03:32:26,43.452658,-116.241552,744,21,0,723,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-05-13 03:32:26,41.330756,-94.471059,3,0,0,3,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
3232,NaN,NaN,NaN,West Bank and Gaza,2020-05-13 03:32:26,31.952200,35.233200,375,2,308,65,West Bank and Gaza
3233,NaN,NaN,NaN,Western Sahara,2020-05-13 03:32:26,24.215500,-12.885800,6,0,6,0,Western Sahara
3234,NaN,NaN,NaN,Yemen,2020-05-13 03:32:26,15.552727,48.516388,65,10,1,54,Yemen
3235,NaN,NaN,NaN,Zambia,2020-05-13 03:32:26,-13.133897,27.849332,441,7,117,317,Zambia
3236,NaN,NaN,NaN,Zimbabwe,2020-05-13 03:32:26,-19.015438,29.154857,36,4,9,23,Zimbabwe

In [82]:
df['Country_Region'].value_counts()

US                                  2972
China                                 33
Canada                                15
France                                11
United Kingdom                        11
Australia                              8
Netherlands                            5
Denmark                                3
Luxembourg                             1
Tunisia                                1
Singapore                              1
Cyprus                                 1
Senegal                                1
Maldives                               1
San Marino                             1
Guinea                                 1
Rwanda                                 1
Russia                                 1
Malaysia                               1
Sri Lanka                              1
Turkey                                 1
India                                  1
Bahamas                                1
Switzerland                            1
Nigeria                                1
Jordan                                 1
South Africa                           1
Saint Vincent and the Grenadines       1
Libya                                  1
Barbados                               1
Egypt                                  1
Uzbekistan                             1
Bahrain                                1
Greece                                 1
Lithuania                              1
Serbia                                 1
Pakistan                               1
Uganda                                 1
Angola                                 1
Dominican Republic                     1
Ghana                                  1
Iran                                   1
Uruguay                                1
Guinea-Bissau                          1
Comoros                                1
Spain                                  1
Bhutan                                 1
Kenya                                  1
Colombia                               1
Grenada                                1
Belize                                 1
Belarus                                1
Romania                                1
Slovenia                               1
Cote d'Ivoire                          1
Seychelles                             1
Iraq                                   1
Burundi                                1
Nepal                                  1
Somalia                                1
Norway                                 1
Ethiopia                               1
Tanzania                               1
Eswatini                               1
Finland                                1
Bulgaria                               1
Diamond Princess                       1
Eritrea                                1
Gabon                                  1
Papua New Guinea                       1
Lebanon                                1
Georgia                                1
New Zealand                            1
MS Zaandam                             1
North Macedonia                        1
Slovakia                               1
Trinidad and Tobago                    1
Mozambique                             1
Albania                                1
Liechtenstein                          1
Japan                                  1
Ukraine                                1
Oman                                   1
Liberia                                1
Syria                                  1
Peru                                   1
Kyrgyzstan                             1
Guyana                                 1
Panama                                 1
Bolivia                                1
Chile                                  1
Haiti                                  1
Gambia                                 1
Iceland                                1
Saint Kitts and Nevis                  1
Jamaica                                1
United Arab Emirates                   1
Mauritius                              1
Bangladesh                             1
Malawi                                 1
Laos                                   1
Sao Tome and Principe                  1
Bosnia and Herzegovina                 1
Equatorial Guinea                      1
Afghanistan                            1
Austria                                1
Morocco                                1
Cabo Verde                             1
Latvia                                 1
Venezuela                              1
Hungary                                1
Armenia                                1
Guatemala                              1
Moldova                                1
Botswana                               1
Cameroon                               1
Vietnam                                1
Mexico                                 1
Namibia                                1
Yemen                                  1
Brunei                                 1
Thailand                               1
Chad                                   1
Croatia                                1
West Bank and Gaza                     1
Congo (Brazzaville)                    1
Kosovo                                 1
Montenegro                             1
Czechia                                1
Paraguay                               1
Djibouti                               1
Italy                                  1
Argentina                              1
Kazakhstan                             1
Portugal                               1
Cambodia                               1
Cuba                                   1
Ecuador                                1
Malta                                  1
Sweden                                 1
Azerbaijan                             1
Qatar                                  1
Timor-Leste                            1
Dominica                               1
Mauritania                             1
Burma                                  1
Sierra Leone                           1
Zimbabwe                               1
Suriname                               1
Korea, South                           1
Monaco                                 1
Philippines                            1
Taiwan*                                1
Saudi Arabia                           1
Costa Rica                             1
Central African Republic               1
Tajikistan                             1
Antigua and Barbuda                    1
Sudan                                  1
Israel                                 1
Indonesia                              1
Honduras                               1
Mongolia                               1
Estonia                                1
Zambia                                 1
Poland                                 1
Andorra                                1
Mali                                   1
Brazil                                 1
Madagascar                             1
Algeria                                1
Togo                                   1
Kuwait                                 1
Benin                                  1
Belgium                                1
Saint Lucia                            1
El Salvador                            1
South Sudan                            1
Germany                                1
Niger                                  1
Congo (Kinshasa)                       1
Nicaragua                              1
Western Sahara                         1
Ireland                                1
Burkina Faso                           1
Fiji                                   1
Holy See                               1
Name: Country_Region, dtype: int64

In [83]:
df[df['Country_Region']=='India']

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
3130,NaN,NaN,NaN,India,2020-05-13 03:32:26,20.593684,78.96288,74292,2415,24420,47457,India

In [84]:
df[df['Country_Region']=='United Kingdom']

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
2966,NaN,NaN,Anguilla,United Kingdom,2020-05-13 03:32:26,18.220600,-63.068600,3,0,3,0,"Anguilla, United Kingdom"
2971,NaN,NaN,Bermuda,United Kingdom,2020-05-13 03:32:26,32.307800,-64.750500,121,8,66,47,"Bermuda, United Kingdom"
2974,NaN,NaN,British Virgin Islands,United Kingdom,2020-05-13 03:32:26,18.420700,-64.640000,7,1,4,2,"British Virgin Islands, United Kingdom"
2975,NaN,NaN,Cayman Islands,United Kingdom,2020-05-13 03:32:26,19.313300,-81.254600,85,1,50,34,"Cayman Islands, United Kingdom"
2976,NaN,NaN,Channel Islands,United Kingdom,2020-05-13 03:32:26,49.372300,-2.364400,547,42,455,50,"Channel Islands, United Kingdom"
2981,NaN,NaN,Falkland Islands (Malvinas),United Kingdom,2020-05-13 03:32:26,-51.796300,-59.523600,13,0,13,0,"Falkland Islands (Malvinas), United Kingdom"
2987,NaN,NaN,Gibraltar,United Kingdom,2020-05-13 03:32:26,36.140800,-5.353600,148,0,144,4,"Gibraltar, United Kingdom"
3004,NaN,NaN,Isle of Man,United Kingdom,2020-05-13 03:32:26,54.236100,-4.548100,331,23,272,36,"Isle of Man, United Kingdom"
3013,NaN,NaN,Montserrat,United Kingdom,2020-05-13 03:32:26,16.742498,-62.187366,11,1,8,2,"Montserrat, United Kingdom"
3046,NaN,NaN,Turks and Caicos Islands,United Kingdom,2020-05-13 03:32:26,21.694000,-71.797900,12,1,8,3,"Turks and Caicos Islands, United Kingdom"
3227,NaN,NaN,NaN,United Kingdom,2020-05-13 03:32:26,55.378100,-3.436000,226463,32692,0,193771,United Kingdom

In [85]:
df

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-05-13 03:32:26,34.223334,-82.461707,34,0,0,34,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-05-13 03:32:26,30.295065,-92.414197,152,11,0,141,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-05-13 03:32:26,37.767072,-75.632346,530,7,0,523,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-05-13 03:32:26,43.452658,-116.241552,744,21,0,723,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-05-13 03:32:26,41.330756,-94.471059,3,0,0,3,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
3232,NaN,NaN,NaN,West Bank and Gaza,2020-05-13 03:32:26,31.952200,35.233200,375,2,308,65,West Bank and Gaza
3233,NaN,NaN,NaN,Western Sahara,2020-05-13 03:32:26,24.215500,-12.885800,6,0,6,0,Western Sahara
3234,NaN,NaN,NaN,Yemen,2020-05-13 03:32:26,15.552727,48.516388,65,10,1,54,Yemen
3235,NaN,NaN,NaN,Zambia,2020-05-13 03:32:26,-13.133897,27.849332,441,7,117,317,Zambia
3236,NaN,NaN,NaN,Zimbabwe,2020-05-13 03:32:26,-19.015438,29.154857,36,4,9,23,Zimbabwe

In [86]:
df['Country_Region'].unique()

array(['US', 'Canada', 'United Kingdom', 'China', 'Netherlands',
       'Australia', 'Denmark', 'France', 'Afghanistan', 'Albania',
       'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Central African Republic',
       'Chad', 'Chile', 'Colombia', 'Comoros', 'Congo (Brazzaville)',
       'Congo (Kinshasa)', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czechia', 'Diamond Princess', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Korea, South', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Namibia',
       'Nepal', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan*',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'Uruguay', 'Uzbekistan', 'Venezuela',
       'Vietnam', 'West Bank and Gaza', 'Western Sahara', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [87]:
countries_with_province = df[pd.notnull(df['Province_State'])]

In [88]:
countries_with_province['Province_State'].nunique()

137

In [89]:
countries_with_province['Country_Region'].nunique()

8

In [90]:
countries_with_province['Country_Region'].unique()

array(['US', 'Canada', 'United Kingdom', 'China', 'Netherlands',
       'Australia', 'Denmark', 'France'], dtype=object)

In [91]:
countries_with_province[countries_with_province['Country_Region']=='US']

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-05-13 03:32:26,34.223334,-82.461707,34,0,0,34,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-05-13 03:32:26,30.295065,-92.414197,152,11,0,141,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-05-13 03:32:26,37.767072,-75.632346,530,7,0,523,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-05-13 03:32:26,43.452658,-116.241552,744,21,0,723,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-05-13 03:32:26,41.330756,-94.471059,3,0,0,3,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2992,66.0,NaN,Guam,US,2020-05-13 03:32:26,13.444300,144.793700,152,5,0,147,"Guam, US"
3019,69.0,NaN,Northern Mariana Islands,US,2020-05-13 03:32:26,15.097900,145.673900,19,2,0,17,"Northern Mariana Islands, US"
3025,72.0,NaN,Puerto Rico,US,2020-05-13 03:32:26,18.220800,-66.590100,2299,114,0,2185,"Puerto Rico, US"
3030,NaN,NaN,Recovered,US,2020-05-13 03:32:26,NaN,NaN,0,0,230287,-229725,"Recovered, US"
3048,78.0,NaN,Virgin Islands,US,2020-05-13 03:32:26,18.335800,-64.896300,69,6,0,63,"Virgin Islands, US"

In [92]:
countries_with_province.groupby(['Country_Region']).count()

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
Australia,0,0,8,8,8,8,8,8,8,8,8
Canada,0,0,15,15,12,12,15,15,15,15,15
China,0,0,33,33,33,33,33,33,33,33,33
Denmark,0,0,2,2,2,2,2,2,2,2,2
France,0,0,10,10,10,10,10,10,10,10,10
Netherlands,0,0,4,4,4,4,4,4,4,4,4
US,2962,2965,2972,2972,2910,2910,2972,2972,2972,2972,2972
United Kingdom,0,0,10,10,10,10,10,10,10,10,10

In [93]:
countries_with_province['Province_State'].value_counts()

Texas                               221
Georgia                             161
Virginia                            134
Kentucky                            114
Missouri                            103
Illinois                            100
North Carolina                      100
Tennessee                            97
Iowa                                 97
Indiana                              93
Ohio                                 89
Kansas                               86
Minnesota                            85
Michigan                             84
Mississippi                          82
Oklahoma                             74
Arkansas                             74
Nebraska                             72
Wisconsin                            70
Alabama                              68
Pennsylvania                         68
Florida                              68
Louisiana                            65
Colorado                             62
New York                             59
California                           56
West Virginia                        53
South Dakota                         53
South Carolina                       47
Washington                           40
North Dakota                         40
Idaho                                36
Oregon                               34
New Mexico                           33
Montana                              32
Maryland                             25
Wyoming                              23
New Jersey                           22
Maine                                17
Nevada                               17
Arizona                              16
Alaska                               15
Vermont                              15
Massachusetts                        14
Utah                                 14
New Hampshire                        11
Connecticut                           9
Rhode Island                          6
Hawaii                                6
Delaware                              4
Diamond Princess                      2
Recovered                             2
Grand Princess                        2
Hebei                                 1
Hainan                                1
Ontario                               1
Guangxi                               1
Inner Mongolia                        1
Tibet                                 1
British Columbia                      1
Ningxia                               1
Fujian                                1
Macau                                 1
Faroe Islands                         1
Victoria                              1
Gansu                                 1
Jiangxi                               1
Montserrat                            1
Guam                                  1
New South Wales                       1
Shanxi                                1
Greenland                             1
Guizhou                               1
Western Australia                     1
Gibraltar                             1
Channel Islands                       1
Sichuan                               1
Saskatchewan                          1
British Virgin Islands                1
Mayotte                               1
Tianjin                               1
Shanghai                              1
Newfoundland and Labrador             1
Jiangsu                               1
Northern Territory                    1
Australian Capital Territory          1
Henan                                 1
Xinjiang                              1
St Martin                             1
Anhui                                 1
Falkland Islands (Malvinas)           1
Shandong                              1
Martinique                            1
Yunnan                                1
District of Columbia                  1
Anguilla                              1
Guadeloupe                            1
Isle of Man                           1
Puerto Rico                           1
Prince Edward Island                  1
Northwest Territories                 1
Cayman Islands                        1
Turks and Caicos Islands              1
Saint Barthelemy                      1
Manitoba                              1
Hubei                                 1
Quebec                                1
Zhejiang                              1
Guangdong                             1
Heilongjiang                          1
South Australia                       1
Reunion                               1
Beijing                               1
Bonaire, Sint Eustatius and Saba      1
New Brunswick                         1
Virgin Islands                        1
Shaanxi                               1
Liaoning                              1
Saint Pierre and Miquelon             1
French Guiana                         1
Northern Mariana Islands              1
Queensland                            1
Tasmania                              1
Alberta                               1
Hong Kong                             1
Qinghai                               1
Curacao                               1
Nova Scotia                           1
Chongqing                             1
Sint Maarten                          1
New Caledonia                         1
Hunan                                 1
Aruba                                 1
Jilin                                 1
Bermuda                               1
Yukon                                 1
French Polynesia                      1
Name: Province_State, dtype: int64

In [94]:
countries_without_province = df[pd.isnull(df['Province_State'])]

In [95]:
countries_without_province

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
3054,NaN,NaN,NaN,Afghanistan,2020-05-13 03:32:26,33.939110,67.709953,4963,127,610,4226,Afghanistan
3055,NaN,NaN,NaN,Albania,2020-05-13 03:32:26,41.153300,20.168300,876,31,682,163,Albania
3056,NaN,NaN,NaN,Algeria,2020-05-13 03:32:26,28.033900,1.659600,6067,515,2998,2554,Algeria
3057,NaN,NaN,NaN,Andorra,2020-05-13 03:32:26,42.506300,1.521800,758,48,568,142,Andorra
3058,NaN,NaN,NaN,Angola,2020-05-13 03:32:26,-11.202700,17.873900,45,2,13,30,Angola
3059,NaN,NaN,NaN,Antigua and Barbuda,2020-05-13 03:32:26,17.060800,-61.796400,25,3,19,3,Antigua and Barbuda
3060,NaN,NaN,NaN,Argentina,2020-05-13 03:32:26,-38.416100,-63.616700,6563,319,1862,4382,Argentina
3061,NaN,NaN,NaN,Armenia,2020-05-13 03:32:26,40.069100,45.038200,3538,47,1430,2061,Armenia
3062,NaN,NaN,NaN,Austria,2020-05-13 03:32:26,47.516200,14.550100,15961,623,14148,1190,Austria
3063,NaN,NaN,NaN,Azerbaijan,2020-05-13 03:32:26,40.143100,47.576900,2693,33,1680,980,Azerbaijan
3064,NaN,NaN,NaN,Bahamas,2020-05-13 03:32:26,25.025885,-78.035889,93,11,39,43,Bahamas
3065,NaN,NaN,NaN,Bahrain,2020-05-13 03:32:26,26.027500,50.550000,5531,9,2192,3330,Bahrain
3066,NaN,NaN,NaN,Bangladesh,2020-05-13 03:32:26,23.685000,90.356300,16660,250,3147,13263,Bangladesh
3067,NaN,NaN,NaN,Barbados,2020-05-13 03:32:26,13.193900,-59.543200,85,7,57,21,Barbados
3068,NaN,NaN,NaN,Belarus,2020-05-13 03:32:26,53.709800,27.953400,24873,142,6974,17757,Belarus
3069,NaN,NaN,NaN,Belgium,2020-05-13 03:32:26,50.833300,4.469936,53779,8761,13732,31286,Belgium
3070,NaN,NaN,NaN,Belize,2020-05-13 03:32:26,17.189900,-88.497600,18,2,16,0,Belize
3071,NaN,NaN,NaN,Benin,2020-05-13 03:32:26,9.307700,2.315800,327,2,76,249,Benin
3072,NaN,NaN,NaN,Bhutan,2020-05-13 03:32:26,27.514200,90.433600,11,0,5,6,Bhutan
3073,NaN,NaN,NaN,Bolivia,2020-05-13 03:32:26,-16.290200,-63.588700,2964,128,313,2523,Bolivia
3074,NaN,NaN,NaN,Bosnia and Herzegovina,2020-05-13 03:32:26,43.915900,17.679100,2158,117,1168,873,Bosnia and Herzegovina
3075,NaN,NaN,NaN,Botswana,2020-05-13 03:32:26,-22.328500,24.684900,24,1,17,6,Botswana
3076,NaN,NaN,NaN,Brazil,2020-05-13 03:32:26,-14.235000,-51.925300,178214,12461,72597,93156,Brazil
3077,NaN,NaN,NaN,Brunei,2020-05-13 03:32:26,4.535300,114.727700,141,1,134,6,Brunei
3078,NaN,NaN,NaN,Bulgaria,2020-05-13 03:32:26,42.733900,25.485800,2023,95,476,1452,Bulgaria
3079,NaN,NaN,NaN,Burkina Faso,2020-05-13 03:32:26,12.238300,-1.561600,766,51,588,127,Burkina Faso
3080,NaN,NaN,NaN,Burma,2020-05-13 03:32:26,21.916200,95.956000,180,6,76,98,Burma
3081,NaN,NaN,NaN,Burundi,2020-05-13 03:32:26,-3.373100,29.918900,15,1,7,7,Burundi
3082,NaN,NaN,NaN,Cabo Verde,2020-05-13 03:32:26,16.538800,-23.041800,267,2,58,207,Cabo Verde
3083,NaN,NaN,NaN,Cambodia,2020-05-13 03:32:26,11.550000,104.916700,122,0,121,1,Cambodia
3084,NaN,NaN,NaN,Cameroon,2020-05-13 03:32:26,3.848000,11.502100,2689,125,1524,1040,Cameroon
3085,NaN,NaN,NaN,Central African Republic,2020-05-13 03:32:26,6.611100,20.939400,143,0,10,133,Central African Republic
3086,NaN,NaN,NaN,Chad,2020-05-13 03:32:26,15.454200,18.732200,357,40,76,241,Chad
3087,NaN,NaN,NaN,Chile,2020-05-13 03:32:26,-35.675100,-71.543000,31721,335,14125,17261,Chile
3088,NaN,NaN,NaN,Colombia,2020-05-13 03:32:26,4.570900,-74.297300,12272,493,2971,8808,Colombia
3089,NaN,NaN,NaN,Comoros,2020-05-13 03:32:26,-11.645500,43.333300,11,1,0,10,Comoros
3090,NaN,NaN,NaN,Congo (Brazzaville),2020-05-13 03:32:26,-4.263400,15.283200,333,11,53,269,Congo (Brazzaville)
3091,NaN,NaN,NaN,Congo (Kinshasa),2020-05-13 03:32:26,-4.322447,15.307045,1102,44,146,912,Congo (Kinshasa)
3092,NaN,NaN,NaN,Costa Rica,2020-05-13 03:32:26,9.748900,-83.753400,804,7,520,277,Costa Rica
3093,NaN,NaN,NaN,Cote d'Ivoire,2020-05-13 03:32:26,7.540000,-5.547100,1857,21,820,1016,Cote d'Ivoire
3094,NaN,NaN,NaN,Croatia,2020-05-13 03:32:26,45.100000,15.200000,2207,91,1808,308,Croatia
3095,NaN,NaN,NaN,Cuba,2020-05-13 03:32:26,21.521757,-77.781167,1804,78,1277,449,Cuba
3096,NaN,NaN,NaN,Cyprus,2020-05-13 03:32:26,35.126400,33.429900,903,16,449,438,Cyprus
3097,NaN,NaN,NaN,Czechia,2020-05-13 03:32:26,49.817500,15.473000,8221,283,4889,3049,Czechia
3098,NaN,NaN,NaN,Denmark,2020-05-13 03:32:26,56.263900,9.501800,10591,527,8580,1484,Denmark
3099,NaN,NaN,NaN,Diamond Princess,2020-05-13 03:32:26,NaN,NaN,712,13,651,48,Diamond Princess
3100,NaN,NaN,NaN,Djibouti,2020-05-13 03:32:26,11.825100,42.590300,1256,3,886,367,Djibouti
3101,NaN,NaN,NaN,Dominica,2020-05-13 03:32:26,15.415000,-61.371000,16,0,15,1,Dominica
3102,NaN,NaN,NaN,Dominican Republic,2020-05-13 03:32:26,18.735700,-70.162700,10900,402,3221,7277,Dominican Republic
3103,NaN,NaN,NaN,Ecuador,2020-05-13 03:32:26,-1.831200,-78.183400,30419,2327,3433,24659,Ecuador
3104,NaN,NaN,NaN,Egypt,2020-05-13 03:32:26,26.820553,30.802498,10093,544,2326,7223,Egypt
3105,NaN,NaN,NaN,El Salvador,2020-05-13 03:32:26,13.794200,-88.896500,998,20,349,629,El Salvador
3106,NaN,NaN,NaN,Equatorial Guinea,2020-05-13 03:32:26,1.650800,10.267900,439,4,13,422,Equatorial Guinea
3107,NaN,NaN,NaN,Eritrea,2020-05-13 03:32:26,15.179400,39.782300,39,0,38,1,Eritrea
3108,NaN,NaN,NaN,Estonia,2020-05-13 03:32:26,58.595300,25.013600,1746,61,777,908,Estonia
3109,NaN,NaN,NaN,Eswatini,2020-05-13 03:32:26,-26.522500,31.465900,184,2,28,154,Eswatini
3110,NaN,NaN,NaN,Ethiopia,2020-05-13 03:32:26,9.145000,40.489700,261,5,106,150,Ethiopia
3111,NaN,NaN,NaN,Fiji,2020-05-13 03:32:26,-17.713400,178.065000,18,0,14,4,Fiji
3112,NaN,NaN,NaN,Finland,2020-05-13 03:32:26,61.924110,25.748151,6003,275,4300,1428,Finland
3113,NaN,NaN,NaN,France,2020-05-13 03:32:26,46.227600,2.213700,176198,26951,56615,92632,France
3114,NaN,NaN,NaN,Gabon,2020-05-13 03:32:26,-0.803700,11.609400,863,9,137,717,Gabon
3115,NaN,NaN,NaN,Gambia,2020-05-13 03:32:26,13.443200,-15.310100,22,1,10,11,Gambia
3116,NaN,NaN,NaN,Georgia,2020-05-13 03:32:26,42.315400,43.356900,642,11,349,282,Georgia
3117,NaN,NaN,NaN,Germany,2020-05-13 03:32:26,51.165691,10.451526,173171,7738,147200,18233,Germany
3118,NaN,NaN,NaN,Ghana,2020-05-13 03:32:26,7.946500,-1.023200,5127,22,494,4611,Ghana
3119,NaN,NaN,NaN,Greece,2020-05-13 03:32:26,39.074200,21.824300,2744,152,1374,1218,Greece
3120,NaN,NaN,NaN,Grenada,2020-05-13 03:32:26,12.116500,-61.679000,21,0,13,8,Grenada
3121,NaN,NaN,NaN,Guatemala,2020-05-13 03:32:26,15.783500,-90.230800,1199,27,120,1052,Guatemala
3122,NaN,NaN,NaN,Guinea,2020-05-13 03:32:26,9.945600,-9.696600,2298,11,816,1471,Guinea
3123,NaN,NaN,NaN,Guinea-Bissau,2020-05-13 03:32:26,11.803700,-15.180400,820,3,26,791,Guinea-Bissau
3124,NaN,NaN,NaN,Guyana,2020-05-13 03:32:26,4.860416,-58.930180,113,10,36,67,Guyana
3125,NaN,NaN,NaN,Haiti,2020-05-13 03:32:26,18.971200,-72.285200,219,18,17,184,Haiti
3126,NaN,NaN,NaN,Holy See,2020-05-13 03:32:26,41.902900,12.453400,12,0,2,10,Holy See
3127,NaN,NaN,NaN,Honduras,2020-05-13 03:32:26,15.200000,-86.241900,2080,121,211,1748,Honduras
3128,NaN,NaN,NaN,Hungary,2020-05-13 03:32:26,47.162500,19.503300,3313,425,1007,1881,Hungary
3129,NaN,NaN,NaN,Iceland,2020-05-13 03:32:26,64.963100,-19.020800,1801,10,1776,15,Iceland
3130,NaN,NaN,NaN,India,2020-05-13 03:32:26,20.593684,78.962880,74292,2415,24420,47457,India
3131,NaN,NaN,NaN,Indonesia,2020-05-13 03:32:26,-0.789300,113.921300,14749,1007,3063,10679,Indonesia
3132,NaN,NaN,NaN,Iran,2020-05-13 03:32:26,32.427908,53.688046,110767,6733,88357,15677,Iran
3133,NaN,NaN,NaN,Iraq,2020-05-13 03:32:26,33.223191,43.679291,2913,112,1903,898,Iraq
3134,NaN,NaN,NaN,Ireland,2020-05-13 03:32:26,53.142400,-7.692100,23242,1488,17110,4644,Ireland
3135,NaN,NaN,NaN,Israel,2020-05-13 03:32:26,31.046051,34.851612,16529,260,12083,4186,Israel
3136,NaN,NaN,NaN,Italy,2020-05-13 03:32:26,41.871940,12.567380,221216,30911,109039,81266,Italy
3137,NaN,NaN,NaN,Jamaica,2020-05-13 03:32:26,18.109600,-77.297500,507,9,100,398,Jamaica
3138,NaN,NaN,NaN,Japan,2020-05-13 03:32:26,36.204824,138.252924,15968,657,8531,6780,Japan
3139,NaN,NaN,NaN,Jordan,2020-05-13 03:32:26,31.240000,36.510000,576,9,390,177,Jordan
3140,NaN,NaN,NaN,Kazakhstan,2020-05-13 03:32:26,48.019600,66.923700,5279,32,2223,3024,Kazakhstan
3141,NaN,NaN,NaN,Kenya,2020-05-13 03:32:26,-0.023600,37.906200,715,36,259,420,Kenya
3142,NaN,NaN,NaN,"Korea, South",2020-05-13 03:32:26,35.907757,127.766922,10962,259,9695,1008,"Korea, South"
3143,NaN,NaN,NaN,Kosovo,2020-05-13 03:32:26,42.602636,20.902977,919,29,671,219,Kosovo
3144,NaN,NaN,NaN,Kuwait,2020-05-13 03:32:26,29.311660,47.481766,10277,75,3101,7101,Kuwait
3145,NaN,NaN,NaN,Kyrgyzstan,2020-05-13 03:32:26,41.204380,74.766098,1037,12,709,316,Kyrgyzstan
3146,NaN,NaN,NaN,Laos,2020-05-13 03:32:26,19.856270,102.495496,19,0,13,6,Laos
3147,NaN,NaN,NaN,Latvia,2020-05-13 03:32:26,56.879600,24.603200,950,18,627,305,Latvia
3148,NaN,NaN,NaN,Lebanon,2020-05-13 03:32:26,33.854700,35.862300,870,26,234,610,Lebanon
3149,NaN,NaN,NaN,Liberia,2020-05-13 03:32:26,6.428055,-9.429499,211,20,85,106,Liberia
3150,NaN,NaN,NaN,Libya,2020-05-13 03:32:26,26.335100,17.228331,64,3,28,33,Libya
3151,NaN,NaN,NaN,Liechtenstein,2020-05-13 03:32:26,47.140000,9.550000,82,1,55,26,Liechtenstein
3152,NaN,NaN,NaN,Lithuania,2020-05-13 03:32:26,55.169400,23.881300,1491,50,850,591,Lithuania
3153,NaN,NaN,NaN,Luxembourg,2020-05-13 03:32:26,49.815300,6.129600,3894,102,3610,182,Luxembourg
3154,NaN,NaN,NaN,MS Zaandam,2020-05-13 03:32:26,NaN,NaN,9,2,0,7,MS Zaandam
3155,NaN,NaN,NaN,Madagascar,2020-05-13 03:32:26,-18.766947,46.869107,186,0,101,85,Madagascar
3156,NaN,NaN,NaN,Malawi,2020-05-13 03:32:26,-13.254308,34.301525,57,3,24,30,Malawi
3157,NaN,NaN,NaN,Malaysia,2020-05-13 03:32:26,4.210484,101.975766,6742,109,5223,1410,Malaysia
3158,NaN,NaN,NaN,Maldives,2020-05-13 03:32:26,3.202800,73.220700,904,3,29,872,Maldives
3159,NaN,NaN,NaN,Mali,2020-05-13 03:32:26,17.570692,-3.996166,730,40,398,292,Mali
3160,NaN,NaN,NaN,Malta,2020-05-13 03:32:26,35.937500,14.375400,506,5,434,67,Malta
3161,NaN,NaN,NaN,Mauritania,2020-05-13 03:32:26,21.007900,-10.940800,9,1,6,2,Mauritania
3162,NaN,NaN,NaN,Mauritius,2020-05-13 03:32:26,-20.348404,57.552152,332,10,322,0,Mauritius
3163,NaN,NaN,NaN,Mexico,2020-05-13 03:32:26,23.634500,-102.552800,38324,3926,25935,8463,Mexico
3164,NaN,NaN,NaN,Moldova,2020-05-13 03:32:26,47.411600,28.369900,5154,182,2069,2903,Moldova
3165,NaN,NaN,NaN,Monaco,2020-05-13 03:32:26,43.733300,7.416700,96,4,85,7,Monaco
3166,NaN,NaN,NaN,Mongolia,2020-05-13 03:32:26,46.862500,103.846700,42,0,15,27,Mongolia
3167,NaN,NaN,NaN,Montenegro,2020-05-13 03:32:26,42.708678,19.374390,324,9,298,17,Montenegro
3168,NaN,NaN,NaN,Morocco,2020-05-13 03:32:26,31.791700,-7.092600,6418,188,2991,3239,Morocco
3169,NaN,NaN,NaN,Mozambique,2020-05-13 03:32:26,-18.665695,35.529562,104,0,34,70,Mozambique
3170,NaN,NaN,NaN,Namibia,2020-05-13 03:32:26,-22.957600,18.490400,16,0,11,5,Namibia
3171,NaN,NaN,NaN,Nepal,2020-05-13 03:32:26,28.166700,84.250000,217,0,33,184,Nepal
3172,NaN,NaN,NaN,Netherlands,2020-05-13 03:32:26,52.132600,5.291300,42984,5510,0,37474,Netherlands
3173,NaN,NaN,NaN,New Zealand,2020-05-13 03:32:26,-40.900600,174.886000,1497,21,1402,74,New Zealand
3174,NaN,NaN,NaN,Nicaragua,2020-05-13 03:32:26,12.865416,-85.207229,25,8,7,10,Nicaragua
3175,NaN,NaN,NaN,Niger,2020-05-13 03:32:26,17.607789,8.081666,854,47,648,159,Niger
3176,NaN,NaN,NaN,Nigeria,2020-05-13 03:32:26,9.082000,8.675300,4787,158,959,3670,Nigeria
3177,NaN,NaN,NaN,North Macedonia,2020-05-13 03:32:26,41.608600,21.745300,1674,92,1205,377,North Macedonia
3178,NaN,NaN,NaN,Norway,2020-05-13 03:32:26,60.472000,8.468900,8157,228,32,7897,Norway
3179,NaN,NaN,NaN,Oman,2020-05-13 03:32:26,21.512583,55.923255,3721,17,1250,2454,Oman
3180,NaN,NaN,NaN,Pakistan,2020-05-13 03:32:26,30.375300,69.345100,34336,737,8812,24787,Pakistan
3181,NaN,NaN,NaN,Panama,2020-05-13 03:32:26,8.538000,-80.782100,8783,252,6021,2510,Panama
3182,NaN,NaN,NaN,Papua New Guinea,2020-05-13 03:32:26,-6.314993,143.955550,8,0,8,0,Papua New Guinea
3183,NaN,NaN,NaN,Paraguay,2020-05-13 03:32:26,-23.442500,-58.443800,737,10,173,554,Paraguay
3184,NaN,NaN,NaN,Peru,2020-05-13 03:32:26,-9.190000,-75.015200,72059,2057,23324,46678,Peru
3185,NaN,NaN,NaN,Philippines,2020-05-13 03:32:26,12.879721,121.774017,11350,751,2106,8493,Philippines
3186,NaN,NaN,NaN,Poland,2020-05-13 03:32:26,51.919400,19.145100,16921,839,6131,9951,Poland
3187,NaN,NaN,NaN,Portugal,2020-05-13 03:32:26,39.399900,-8.224500,27913,1163,3013,23737,Portugal
3188,NaN,NaN,NaN,Qatar,2020-05-13 03:32:26,25.354800,51.183900,25149,14,3019,22116,Qatar
3189,NaN,NaN,NaN,Romania,2020-05-13 03:32:26,45.943200,24.966800,15778,1002,7685,7091,Romania
3190,NaN,NaN,NaN,Russia,2020-05-13 03:32:26,61.524010,105.318756,232243,2116,43512,186615,Russia
3191,NaN,NaN,NaN,Rwanda,2020-05-13 03:32:26,-1.940300,29.873900,286,0,153,133,Rwanda
3192,NaN,NaN,NaN,Saint Kitts and Nevis,2020-05-13 03:32:26,17.357822,-62.782998,15,0,14,1,Saint Kitts and Nevis
3193,NaN,NaN,NaN,Saint Lucia,2020-05-13 03:32:26,13.909400,-60.978900,18,0,17,1,Saint Lucia
3194,NaN,NaN,NaN,Saint Vincent and the Grenadines,2020-05-13 03:32:26,12.984300,-61.287200,17,0,12,5,Saint Vincent and the Grenadines
3195,NaN,NaN,NaN,San Marino,2020-05-13 03:32:26,43.942400,12.457800,638,41,161,436,San Marino
3196,NaN,NaN,NaN,Sao Tome and Principe,2020-05-13 03:32:26,0.186360,6.613081,208,5,4,199,Sao Tome and Principe
3197,NaN,NaN,NaN,Saudi Arabia,2020-05-13 03:32:26,23.885942,45.079162,42925,264,15257,27404,Saudi Arabia
3198,NaN,NaN,NaN,Senegal,2020-05-13 03:32:26,14.497400,-14.452400,1995,19,742,1234,Senegal
3199,NaN,NaN,NaN,Serbia,2020-05-13 03:32:26,44.016500,21.005900,10243,220,3600,6423,Serbia
3200,NaN,NaN,NaN,Seychelles,2020-05-13 03:32:26,-4.679600,55.492000,11,0,10,1,Seychelles
3201,NaN,NaN,NaN,Sierra Leone,2020-05-13 03:32:26,8.460555,-11.779889,338,19,72,247,Sierra Leone
3202,NaN,NaN,NaN,Singapore,2020-05-13 03:32:26,1.283300,103.833300,24671,21,3851,20799,Singapore
3203,NaN,NaN,NaN,Slovakia,2020-05-13 03:32:26,48.669000,19.699000,1465,27,983,455,Slovakia
3204,NaN,NaN,NaN,Slovenia,2020-05-13 03:32:26,46.151200,14.995500,1461,102,259,1100,Slovenia
3205,NaN,NaN,NaN,Somalia,2020-05-13 03:32:26,5.152149,46.199616,1170,52,126,992,Somalia
3206,NaN,NaN,NaN,South Africa,2020-05-13 03:32:26,-30.559500,22.937500,11350,206,4357,6787,South Africa
3207,NaN,NaN,NaN,South Sudan,2020-05-13 03:32:26,6.877000,31.307000,194,0,2,192,South Sudan
3208,NaN,NaN,NaN,Spain,2020-05-13 03:32:26,40.463667,-3.749220,228030,26920,138980,62130,Spain
3209,NaN,NaN,NaN,Sri Lanka,2020-05-13 03:32:26,7.873054,80.771797,889,9,366,514,Sri Lanka
3210,NaN,NaN,NaN,Sudan,2020-05-13 03:32:26,12.862800,30.217600,1661,80,173,1408,Sudan
3211,NaN,NaN,NaN,Suriname,2020-05-13 03:32:26,3.919300,-56.027800,10,1,9,0,Suriname
3212,NaN,NaN,NaN,Sweden,2020-05-13 03:32:26,60.128161,18.643501,27272,3313,4971,18988,Sweden
3213,NaN,NaN,NaN,Switzerland,2020-05-13 03:32:26,46.818200,8.227500,30380,1867,26800,1713,Switzerland
3214,NaN,NaN,NaN,Syria,2020-05-13 03:32:26,34.802075,38.996815,47,3,29,15,Syria
3215,NaN,NaN,NaN,Taiwan*,2020-05-13 03:32:26,23.700000,121.000000,440,7,372,61,Taiwan*
3216,NaN,NaN,NaN,Tajikistan,2020-05-13 03:32:26,38.861034,71.276093,729,21,0,708,Tajikistan
3217,NaN,NaN,NaN,Tanzania,2020-05-13 03:32:26,-6.369028,34.888822,509,21,183,305,Tanzania
3218,NaN,NaN,NaN,Thailand,2020-05-13 03:32:26,15.870032,100.992541,3017,56,2798,163,Thailand
3219,NaN,NaN,NaN,Timor-Leste,2020-05-13 03:32:26,-8.874217,125.727539,24,0,21,3,Timor-Leste
3220,NaN,NaN,NaN,Togo,2020-05-13 03:32:26,8.619500,0.824800,199,11,92,96,Togo
3221,NaN,NaN,NaN,Trinidad and Tobago,2020-05-13 03:32:26,10.691800,-61.222500,116,8,107,1,Trinidad and Tobago
3222,NaN,NaN,NaN,Tunisia,2020-05-13 03:32:26,33.886917,9.537499,1032,45,740,247,Tunisia
3223,NaN,NaN,NaN,Turkey,2020-05-13 03:32:26,38.963700,35.243300,141475,3894,98889,38692,Turkey
3224,NaN,NaN,NaN,Uganda,2020-05-13 03:32:26,1.373333,32.290275,129,0,55,74,Uganda
3225,NaN,NaN,NaN,Ukraine,2020-05-13 03:32:26,48.379400,31.165600,16023,425,3373,12225,Ukraine
3226,NaN,NaN,NaN,United Arab Emirates,2020-05-13 03:32:26,23.424076,53.847818,19661,203,6012,13446,United Arab Emirates
3227,NaN,NaN,NaN,United Kingdom,2020-05-13 03:32:26,55.378100,-3.436000,226463,32692,0,193771,United Kingdom
3228,NaN,NaN,NaN,Uruguay,2020-05-13 03:32:26,-32.522800,-55.765800,717,19,532,166,Uruguay
3229,NaN,NaN,NaN,Uzbekistan,2020-05-13 03:32:26,41.377491,64.585262,2519,10,2010,499,Uzbekistan
3230,NaN,NaN,NaN,Venezuela,2020-05-13 03:32:26,6.423800,-66.589700,423,10,220,193,Venezuela
3231,NaN,NaN,NaN,Vietnam,2020-05-13 03:32:26,14.058324,108.277199,288,0,252,36,Vietnam
3232,NaN,NaN,NaN,West Bank and Gaza,2020-05-13 03:32:26,31.952200,35.233200,375,2,308,65,West Bank and Gaza
3233,NaN,NaN,NaN,Western Sahara,2020-05-13 03:32:26,24.215500,-12.885800,6,0,6,0,Western Sahara
3234,NaN,NaN,NaN,Yemen,2020-05-13 03:32:26,15.552727,48.516388,65,10,1,54,Yemen
3235,NaN,NaN,NaN,Zambia,2020-05-13 03:32:26,-13.133897,27.849332,441,7,117,317,Zambia
3236,NaN,NaN,NaN,Zimbabwe,2020-05-13 03:32:26,-19.015438,29.154857,36,4,9,23,Zimbabwe

In [96]:
countries_without_province['Country_Region'].value_counts()

Haiti                               1
Pakistan                            1
Kyrgyzstan                          1
Belgium                             1
Sweden                              1
Saint Lucia                         1
El Salvador                         1
Guyana                              1
Panama                              1
Diamond Princess                    1
Germany                             1
Brazil                              1
Congo (Kinshasa)                    1
Bolivia                             1
Chile                               1
Ireland                             1
Gambia                              1
Iceland                             1
Peru                                1
Niger                               1
MS Zaandam                          1
Benin                               1
Syria                               1
Slovenia                            1
Mauritius                           1
Gabon                               1
Albania                             1
Qatar                               1
Switzerland                         1
Dominica                            1
Togo                                1
Liechtenstein                       1
Japan                               1
Uzbekistan                          1
Ukraine                             1
Russia                              1
Mali                                1
Israel                              1
Madagascar                          1
Algeria                             1
Oman                                1
Liberia                             1
Estonia                             1
Slovakia                            1
New Zealand                         1
Cote d'Ivoire                       1
Mozambique                          1
Saudi Arabia                        1
Bulgaria                            1
Central African Republic            1
Taiwan*                             1
Eritrea                             1
Antigua and Barbuda                 1
Sudan                               1
Papua New Guinea                    1
Suriname                            1
Korea, South                        1
Kuwait                              1
Indonesia                           1
Lebanon                             1
Romania                             1
Honduras                            1
Mauritania                          1
Jamaica                             1
Georgia                             1
Western Sahara                      1
Holy See                            1
Timor-Leste                         1
Norway                              1
Burkina Faso                        1
Philippines                         1
Andorra                             1
Seychelles                          1
Zambia                              1
Ecuador                             1
Iraq                                1
Thailand                            1
Burundi                             1
Nicaragua                           1
Burma                               1
Nepal                               1
Sierra Leone                        1
Greece                              1
Azerbaijan                          1
Luxembourg                          1
Ethiopia                            1
Tanzania                            1
Eswatini                            1
Finland                             1
Netherlands                         1
Bosnia and Herzegovina              1
Trinidad and Tobago                 1
Vietnam                             1
Paraguay                            1
Italy                               1
Argentina                           1
South Africa                        1
Kenya                               1
Dominican Republic                  1
Ghana                               1
Kazakhstan                          1
Iran                                1
Uruguay                             1
Cambodia                            1
Yemen                               1
Guinea-Bissau                       1
Cuba                                1
Cameroon                            1
Comoros                             1
Spain                               1
Malta                               1
Bhutan                              1
Brunei                              1
Djibouti                            1
Angola                              1
Colombia                            1
Czechia                             1
Somalia                             1
United Arab Emirates                1
Saint Vincent and the Grenadines    1
Mongolia                            1
Saint Kitts and Nevis               1
Chad                                1
Denmark                             1
Egypt                               1
Fiji                                1
Poland                              1
Bahrain                             1
Kosovo                              1
West Bank and Gaza                  1
Lithuania                           1
Serbia                              1
Congo (Brazzaville)                 1
Uganda                              1
Montenegro                          1
Malawi                              1
United Kingdom                      1
Barbados                            1
Libya                               1
India                               1
Morocco                             1
Cabo Verde                          1
Latvia                              1
Venezuela                           1
Nigeria                             1
Jordan                              1
Hungary                             1
Armenia                             1
Rwanda                              1
Turkey                              1
Monaco                              1
Croatia                             1
Belarus                             1
Guatemala                           1
North Macedonia                     1
Belize                              1
Moldova                             1
South Sudan                         1
Botswana                            1
Bahamas                             1
Austria                             1
Grenada                             1
Afghanistan                         1
Zimbabwe                            1
France                              1
Namibia                             1
Costa Rica                          1
Sri Lanka                           1
Mexico                              1
Bangladesh                          1
Tunisia                             1
Singapore                           1
Cyprus                              1
Senegal                             1
Laos                                1
Maldives                            1
Malaysia                            1
Tajikistan                          1
San Marino                          1
Sao Tome and Principe               1
Guinea                              1
Equatorial Guinea                   1
Portugal                            1
Name: Country_Region, dtype: int64

In [97]:
countries_without_province['Country_Region'].nunique()

183

In [98]:
pd.set_option('display.max_rows', 500)

In [99]:
countries_without_province.groupby(['Country_Region']).count()

,FIPS,Admin2,Province_State,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
Country_Region,,,,,,,,,,,
Afghanistan,0,0,0,1,1,1,1,1,1,1,1
Albania,0,0,0,1,1,1,1,1,1,1,1
Algeria,0,0,0,1,1,1,1,1,1,1,1
Andorra,0,0,0,1,1,1,1,1,1,1,1
Angola,0,0,0,1,1,1,1,1,1,1,1
Antigua and Barbuda,0,0,0,1,1,1,1,1,1,1,1
Argentina,0,0,0,1,1,1,1,1,1,1,1
Armenia,0,0,0,1,1,1,1,1,1,1,1
Austria,0,0,0,1,1,1,1,1,1,1,1
Azerbaijan,0,0,0,1,1,1,1,1,1,1,1
Bahamas,0,0,0,1,1,1,1,1,1,1,1
Bahrain,0,0,0,1,1,1,1,1,1,1,1
Bangladesh,0,0,0,1,1,1,1,1,1,1,1
Barbados,0,0,0,1,1,1,1,1,1,1,1
Belarus,0,0,0,1,1,1,1,1,1,1,1
Belgium,0,0,0,1,1,1,1,1,1,1,1
Belize,0,0,0,1,1,1,1,1,1,1,1
Benin,0,0,0,1,1,1,1,1,1,1,1
Bhutan,0,0,0,1,1,1,1,1,1,1,1
Bolivia,0,0,0,1,1,1,1,1,1,1,1
Bosnia and Herzegovina,0,0,0,1,1,1,1,1,1,1,1
Botswana,0,0,0,1,1,1,1,1,1,1,1
Brazil,0,0,0,1,1,1,1,1,1,1,1
Brunei,0,0,0,1,1,1,1,1,1,1,1
Bulgaria,0,0,0,1,1,1,1,1,1,1,1
Burkina Faso,0,0,0,1,1,1,1,1,1,1,1
Burma,0,0,0,1,1,1,1,1,1,1,1
Burundi,0,0,0,1,1,1,1,1,1,1,1
Cabo Verde,0,0,0,1,1,1,1,1,1,1,1
Cambodia,0,0,0,1,1,1,1,1,1,1,1
Cameroon,0,0,0,1,1,1,1,1,1,1,1
Central African Republic,0,0,0,1,1,1,1,1,1,1,1
Chad,0,0,0,1,1,1,1,1,1,1,1
Chile,0,0,0,1,1,1,1,1,1,1,1
Colombia,0,0,0,1,1,1,1,1,1,1,1
Comoros,0,0,0,1,1,1,1,1,1,1,1
Congo (Brazzaville),0,0,0,1,1,1,1,1,1,1,1
Congo (Kinshasa),0,0,0,1,1,1,1,1,1,1,1
Costa Rica,0,0,0,1,1,1,1,1,1,1,1
Cote d'Ivoire,0,0,0,1,1,1,1,1,1,1,1
Croatia,0,0,0,1,1,1,1,1,1,1,1
Cuba,0,0,0,1,1,1,1,1,1,1,1
Cyprus,0,0,0,1,1,1,1,1,1,1,1
Czechia,0,0,0,1,1,1,1,1,1,1,1
Denmark,0,0,0,1,1,1,1,1,1,1,1
Diamond Princess,0,0,0,1,0,0,1,1,1,1,1
Djibouti,0,0,0,1,1,1,1,1,1,1,1
Dominica,0,0,0,1,1,1,1,1,1,1,1
Dominican Republic,0,0,0,1,1,1,1,1,1,1,1
Ecuador,0,0,0,1,1,1,1,1,1,1,1
Egypt,0,0,0,1,1,1,1,1,1,1,1
El Salvador,0,0,0,1,1,1,1,1,1,1,1
Equatorial Guinea,0,0,0,1,1,1,1,1,1,1,1
Eritrea,0,0,0,1,1,1,1,1,1,1,1
Estonia,0,0,0,1,1,1,1,1,1,1,1
Eswatini,0,0,0,1,1,1,1,1,1,1,1
Ethiopia,0,0,0,1,1,1,1,1,1,1,1
Fiji,0,0,0,1,1,1,1,1,1,1,1
Finland,0,0,0,1,1,1,1,1,1,1,1
France,0,0,0,1,1,1,1,1,1,1,1
Gabon,0,0,0,1,1,1,1,1,1,1,1
Gambia,0,0,0,1,1,1,1,1,1,1,1
Georgia,0,0,0,1,1,1,1,1,1,1,1
Germany,0,0,0,1,1,1,1,1,1,1,1
Ghana,0,0,0,1,1,1,1,1,1,1,1
Greece,0,0,0,1,1,1,1,1,1,1,1
Grenada,0,0,0,1,1,1,1,1,1,1,1
Guatemala,0,0,0,1,1,1,1,1,1,1,1
Guinea,0,0,0,1,1,1,1,1,1,1,1
Guinea-Bissau,0,0,0,1,1,1,1,1,1,1,1
Guyana,0,0,0,1,1,1,1,1,1,1,1
Haiti,0,0,0,1,1,1,1,1,1,1,1
Holy See,0,0,0,1,1,1,1,1,1,1,1
Honduras,0,0,0,1,1,1,1,1,1,1,1
Hungary,0,0,0,1,1,1,1,1,1,1,1
Iceland,0,0,0,1,1,1,1,1,1,1,1
India,0,0,0,1,1,1,1,1,1,1,1
Indonesia,0,0,0,1,1,1,1,1,1,1,1
Iran,0,0,0,1,1,1,1,1,1,1,1
Iraq,0,0,0,1,1,1,1,1,1,1,1
Ireland,0,0,0,1,1,1,1,1,1,1,1
Israel,0,0,0,1,1,1,1,1,1,1,1
Italy,0,0,0,1,1,1,1,1,1,1,1
Jamaica,0,0,0,1,1,1,1,1,1,1,1
Japan,0,0,0,1,1,1,1,1,1,1,1
Jordan,0,0,0,1,1,1,1,1,1,1,1
Kazakhstan,0,0,0,1,1,1,1,1,1,1,1
Kenya,0,0,0,1,1,1,1,1,1,1,1
"Korea, South",0,0,0,1,1,1,1,1,1,1,1
Kosovo,0,0,0,1,1,1,1,1,1,1,1
Kuwait,0,0,0,1,1,1,1,1,1,1,1
Kyrgyzstan,0,0,0,1,1,1,1,1,1,1,1
Laos,0,0,0,1,1,1,1,1,1,1,1
Latvia,0,0,0,1,1,1,1,1,1,1,1
Lebanon,0,0,0,1,1,1,1,1,1,1,1
Liberia,0,0,0,1,1,1,1,1,1,1,1
Libya,0,0,0,1,1,1,1,1,1,1,1
Liechtenstein,0,0,0,1,1,1,1,1,1,1,1
Lithuania,0,0,0,1,1,1,1,1,1,1,1
Luxembourg,0,0,0,1,1,1,1,1,1,1,1
MS Zaandam,0,0,0,1,0,0,1,1,1,1,1
Madagascar,0,0,0,1,1,1,1,1,1,1,1
Malawi,0,0,0,1,1,1,1,1,1,1,1
Malaysia,0,0,0,1,1,1,1,1,1,1,1
Maldives,0,0,0,1,1,1,1,1,1,1,1
Mali,0,0,0,1,1,1,1,1,1,1,1
Malta,0,0,0,1,1,1,1,1,1,1,1
Mauritania,0,0,0,1,1,1,1,1,1,1,1
Mauritius,0,0,0,1,1,1,1,1,1,1,1
Mexico,0,0,0,1,1,1,1,1,1,1,1
Moldova,0,0,0,1,1,1,1,1,1,1,1
Monaco,0,0,0,1,1,1,1,1,1,1,1
Mongolia,0,0,0,1,1,1,1,1,1,1,1
Montenegro,0,0,0,1,1,1,1,1,1,1,1
Morocco,0,0,0,1,1,1,1,1,1,1,1
Mozambique,0,0,0,1,1,1,1,1,1,1,1
Namibia,0,0,0,1,1,1,1,1,1,1,1
Nepal,0,0,0,1,1,1,1,1,1,1,1
Netherlands,0,0,0,1,1,1,1,1,1,1,1
New Zealand,0,0,0,1,1,1,1,1,1,1,1
Nicaragua,0,0,0,1,1,1,1,1,1,1,1
Niger,0,0,0,1,1,1,1,1,1,1,1
Nigeria,0,0,0,1,1,1,1,1,1,1,1
North Macedonia,0,0,0,1,1,1,1,1,1,1,1
Norway,0,0,0,1,1,1,1,1,1,1,1
Oman,0,0,0,1,1,1,1,1,1,1,1
Pakistan,0,0,0,1,1,1,1,1,1,1,1
Panama,0,0,0,1,1,1,1,1,1,1,1
Papua New Guinea,0,0,0,1,1,1,1,1,1,1,1
Paraguay,0,0,0,1,1,1,1,1,1,1,1
Peru,0,0,0,1,1,1,1,1,1,1,1
Philippines,0,0,0,1,1,1,1,1,1,1,1
Poland,0,0,0,1,1,1,1,1,1,1,1
Portugal,0,0,0,1,1,1,1,1,1,1,1
Qatar,0,0,0,1,1,1,1,1,1,1,1
Romania,0,0,0,1,1,1,1,1,1,1,1
Russia,0,0,0,1,1,1,1,1,1,1,1
Rwanda,0,0,0,1,1,1,1,1,1,1,1
Saint Kitts and Nevis,0,0,0,1,1,1,1,1,1,1,1
Saint Lucia,0,0,0,1,1,1,1,1,1,1,1
Saint Vincent and the Grenadines,0,0,0,1,1,1,1,1,1,1,1
San Marino,0,0,0,1,1,1,1,1,1,1,1
Sao Tome and Principe,0,0,0,1,1,1,1,1,1,1,1
Saudi Arabia,0,0,0,1,1,1,1,1,1,1,1
Senegal,0,0,0,1,1,1,1,1,1,1,1
Serbia,0,0,0,1,1,1,1,1,1,1,1
Seychelles,0,0,0,1,1,1,1,1,1,1,1
Sierra Leone,0,0,0,1,1,1,1,1,1,1,1
Singapore,0,0,0,1,1,1,1,1,1,1,1
Slovakia,0,0,0,1,1,1,1,1,1,1,1
Slovenia,0,0,0,1,1,1,1,1,1,1,1
Somalia,0,0,0,1,1,1,1,1,1,1,1
South Africa,0,0,0,1,1,1,1,1,1,1,1
South Sudan,0,0,0,1,1,1,1,1,1,1,1
Spain,0,0,0,1,1,1,1,1,1,1,1
Sri Lanka,0,0,0,1,1,1,1,1,1,1,1
Sudan,0,0,0,1,1,1,1,1,1,1,1
Suriname,0,0,0,1,1,1,1,1,1,1,1
Sweden,0,0,0,1,1,1,1,1,1,1,1
Switzerland,0,0,0,1,1,1,1,1,1,1,1
Syria,0,0,0,1,1,1,1,1,1,1,1
Taiwan*,0,0,0,1,1,1,1,1,1,1,1
Tajikistan,0,0,0,1,1,1,1,1,1,1,1
Tanzania,0,0,0,1,1,1,1,1,1,1,1
Thailand,0,0,0,1,1,1,1,1,1,1,1
Timor-Leste,0,0,0,1,1,1,1,1,1,1,1
Togo,0,0,0,1,1,1,1,1,1,1,1
Trinidad and Tobago,0,0,0,1,1,1,1,1,1,1,1
Tunisia,0,0,0,1,1,1,1,1,1,1,1
Turkey,0,0,0,1,1,1,1,1,1,1,1
Uganda,0,0,0,1,1,1,1,1,1,1,1
Ukraine,0,0,0,1,1,1,1,1,1,1,1
United Arab Emirates,0,0,0,1,1,1,1,1,1,1,1
United Kingdom,0,0,0,1,1,1,1,1,1,1,1
Uruguay,0,0,0,1,1,1,1,1,1,1,1
Uzbekistan,0,0,0,1,1,1,1,1,1,1,1
Venezuela,0,0,0,1,1,1,1,1,1,1,1
Vietnam,0,0,0,1,1,1,1,1,1,1,1
West Bank and Gaza,0,0,0,1,1,1,1,1,1,1,1
Western Sahara,0,0,0,1,1,1,1,1,1,1,1
Yemen,0,0,0,1,1,1,1,1,1,1,1
Zambia,0,0,0,1,1,1,1,1,1,1,1
Zimbabwe,0,0,0,1,1,1,1,1,1,1,1

In [100]:
list_of_countries_without_proivince = countries_without_province['Country_Region'].unique()

## Get data for India day by day

In [101]:
df1 = pd.read_csv('data/02-22-2020.csv')

In [102]:
df1.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Hubei,Mainland China,2020-02-22T23:33:06,64084,2346,15299
1,Guangdong,Mainland China,2020-02-22T10:03:04,1339,5,728
2,Henan,Mainland China,2020-02-22T14:13:38,1270,19,830
3,Zhejiang,Mainland China,2020-02-22T11:13:13,1205,1,719
4,Hunan,Mainland China,2020-02-22T10:03:04,1013,4,692

In [103]:
df1[df1['Country/Region']=='India']['Confirmed'].values[0]

3

In [104]:
df2 = pd.read_csv('data/04-22-2020.csv')

In [105]:
df2.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-22 23:30:53,34.223334,-82.461707,22,0,0,22,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-22 23:30:53,30.295065,-92.414197,117,7,0,110,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-22 23:30:53,37.767072,-75.632346,59,1,0,58,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-22 23:30:53,43.452658,-116.241552,622,12,0,610,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-22 23:30:53,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [106]:
try:
  print(df2['Country_Region'])
except:
  print(df2['Country/Region'])

0                       US
1                       US
2                       US
3                       US
4                       US
               ...
3094    West Bank and Gaza
3095        Western Sahara
3096                 Yemen
3097                Zambia
3098              Zimbabwe
Name: Country_Region, Length: 3099, dtype: object

# Creating Database for saving data

In [107]:
myclient = pymongo.MongoClient("mongodb://localhost:27017/")
database = myclient["covid-19"]
countries_collection = database["countries"]

# Adding Time series data country wise

## Getting daily data country wise

In [108]:
def get_daily_data_for_country(country, df, valid_date, first_case_found):
    confirmed_cases_count = 0
    death_cases_count = 0
    recovered_cases_count = 0
    active_cases_count = 0
    try:
        confirmed_cases = df[df['Country/Region']==country]['Confirmed']
        death_cases = df[df['Country/Region']==country]['Deaths']
        recovered_cases = df[df['Country/Region']==country]['Recovered']
        if len(confirmed_cases) > 0:
            print("Total number of confirmed cases in Country/Region", country, ' on ', valid_date, ' was ', df[df['Country/Region']==country]['Confirmed'].values[0])
            confirmed_cases_count = df[df['Country/Region']==country]['Confirmed'].values[0]
        if len(death_cases) > 0:
            print("Total number of deaths in Country/Region", country, ' on ', valid_date, ' was ', df[df['Country/Region']==country]['Deaths'].values[0])
            death_cases_count = df[df['Country/Region']==country]['Deaths'].values[0]
        if len(recovered_cases) > 0:
            print("Total number of recovered cases in Country/Region", country, ' on ', valid_date, ' was ', df[df['Country/Region']==country]['Recovered'].values[0])   
            recovered_cases_count = df[df['Country/Region']==country]['Recovered'].values[0]
            active_cases_count = confirmed_cases_count - (recovered_cases_count + death_cases_count)
            return confirmed_cases_count, death_cases_count, recovered_cases_count, active_cases_count, valid_date
        else:
            print('No cases found in Country/Region ', country, ' on ', valid_date)
            return confirmed_cases_count, death_cases_count, recovered_cases_count, active_cases_count, valid_date
    except:
        confirmed_cases = df[df['Country_Region']==country]['Confirmed']
        death_cases = df[df['Country_Region']==country]['Deaths']
        recovered_cases = df[df['Country_Region']==country]['Recovered']
        if len(confirmed_cases) > 0:
            print("Total number of confirmed cases in Country_Region", country, ' on ', valid_date, ' was ', df[df['Country_Region']==country]['Confirmed'].values[0])
            confirmed_cases_count = df[df['Country_Region']==country]['Confirmed'].values[0]
        if len(death_cases) > 0:
            print("Total number of deaths in Country_Region", country, ' on ', valid_date, ' was ', df[df['Country_Region']==country]['Deaths'].values[0])
            death_cases_count = df[df['Country_Region']==country]['Deaths'].values[0]
        if len(recovered_cases) > 0:
            print("Total number of recovered cases in Country_Region", country, ' on ', valid_date, ' was ', df[df['Country_Region']==country]['Recovered'].values[0])   
            recovered_cases_count = df[df['Country_Region']==country]['Recovered'].values[0]
            active_cases_count = confirmed_cases_count - (recovered_cases_count + death_cases_count)
            return confirmed_cases_count, death_cases_count, recovered_cases_count, active_cases_count, valid_date
        else:
            print('No cases found in Country_Region ', country, ' on ', valid_date)
            return confirmed_cases_count, death_cases_count, recovered_cases_count, active_cases_count, valid_date

## Saving daily data country wise

In [109]:
def add_data_for_country_to_db(country,date, total_confirmed, delta_confirmed, total_deaths, delta_deaths, total_recovered, delta_recovered, total_active, delta_active):
    if countries_collection.find({'name': country}).count() >0:
        time_series = []
        date_obj = {
            "date": str(date_of_first_incident),
            "confirmed": {"count": total_confirmed, "delta": delta_confirmed },
            "deaths": {"count": total_deaths, "delta": delta_deaths},
            "recovered": {"count": total_recovered, "delta": delta_recovered},
            "active": {"count":total_active, "delta": delta_active},
        }
        countries_collection.update({'name': country}, {'$push': {'timesSeries': date_obj}}) 
    else:
        time_series = []
        date_obj = [{
        "date": str(date_of_first_incident),
        "confirmed": {"count": total_confirmed, "delta": delta_confirmed },
        "deaths": {"count": total_deaths, "delta": delta_deaths},
        "recovered": {"count": total_recovered, "delta": delta_recovered},
        "active": {"count":total_active, "delta": delta_active},
        }]
        #time_series.append[date_obj]
        datax =  {
            "name": country,
            "coordinates":
            {
                "lat": '0',
                "long": '0'
            },
            "firstIncidentDate": date_of_first_incident,
            "timesSeries":date_obj,
            "lastUpdatedAt": "04-25-2020",
            "province": "NA"

        }
        x = countries_collection.insert_one(datax)

## Iterating daily files country wise

In [110]:
days_since_first_data = (today-first_available_data_date).days
date_iterator = first_available_data_date
first_case_found = False
previous_confirmed_count = 0;
previous_deaths_count = 0;
previous_recovered_count = 0;
previous_active_count = 0;
for country in list_of_countries_without_proivince:
    
    for day in range(days_since_first_data):
        date_iterator_month = str(date_iterator.month) if len(str(date_iterator.month)) > 1 else '0'+str(date_iterator.month)
        date_iterator_day = str(date_iterator.day) if len(str(date_iterator.day)) > 1 else '0'+str(date_iterator.day)
        date_iterator_year = str(date_iterator.year)
        valid_date = date_iterator_month + '-' + date_iterator_day + '-' + date_iterator_year
        valid_file_name = date_iterator_month + '-' + date_iterator_day + '-' + date_iterator_year +'.csv'
        print(country,valid_date)

        #print(day," st day valid date is:",valid_file_name)
        df = pd.read_csv('data/'+valid_file_name)
        df.fillna(0, axis=1,inplace=True)

        total_confirmed, total_deaths, total_recovered, total_active, date_of_first_incident = get_daily_data_for_country(country,df,valid_date,first_case_found)
        delta_confirmed = total_confirmed - previous_confirmed_count
        delta_deaths = total_deaths - previous_deaths_count
        delta_recovered = total_recovered - previous_recovered_count
        delta_active = total_active - previous_active_count
        print('delta confirmed is', delta_confirmed)
        print('delta deaths is', delta_deaths)
        print('delta recovered is', delta_recovered)
        print('delta active is', delta_active)

        previous_confirmed_count = total_confirmed
        previous_deaths_count = total_deaths
        previous_recovered_count = total_recovered
        previous_active_count = total_active

        if total_confirmed > 0:
            if first_case_found == False:
                print('Frist case for', country,  'on' , date_of_first_incident )
                add_data_for_country_to_db(country, date_of_first_incident, int(total_confirmed), int(delta_confirmed), int(total_deaths), int(delta_deaths), int(total_recovered), int(delta_recovered), int(total_active), int(delta_active))
                first_case_found = True
            else:
                add_data_for_country_to_db(country, valid_date, int(total_confirmed), int(delta_confirmed), int(total_deaths), int(delta_deaths), int(total_recovered), int(delta_recovered),int(total_active), int(delta_active))


        date_iterator = date_iterator + datetime.timedelta(days=1)
    days_since_first_data = (today-first_available_data_date).days
    date_iterator = first_available_data_date
    first_case_found = False
    previous_confirmed_count = 0;
    previous_deaths_count = 0;
    previous_recovered_count = 0;

Afghanistan 01-22-2020
No cases found in Country/Region  Afghanistan  on  01-22-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-23-2020
No cases found in Country/Region  Afghanistan  on  01-23-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-24-2020
No cases found in Country/Region  Afghanistan  on  01-24-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-25-2020
No cases found in Country/Region  Afghanistan  on  01-25-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-26-2020
No cases found in Country/Region  Afghanistan  on  01-26-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-27-2020
No cases found in Country/Region  Afghanistan  on  01-27-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-28-2020
No cases found in Country/Region  Afghanistan  on  01-28-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-29-2020
No cases found in Country/Region  Afghanistan  on  01-29-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-30-2020
No cases found in Country/Region  Afghanistan  on  01-30-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 01-31-2020
No cases found in Country/Region  Afghanistan  on  01-31-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-01-2020
No cases found in Country/Region  Afghanistan  on  02-01-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-02-2020
No cases found in Country/Region  Afghanistan  on  02-02-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-03-2020
No cases found in Country/Region  Afghanistan  on  02-03-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-04-2020
No cases found in Country/Region  Afghanistan  on  02-04-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-05-2020
No cases found in Country/Region  Afghanistan  on  02-05-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-06-2020
No cases found in Country/Region  Afghanistan  on  02-06-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-07-2020
No cases found in Country/Region  Afghanistan  on  02-07-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-08-2020
No cases found in Country/Region  Afghanistan  on  02-08-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-09-2020
No cases found in Country/Region  Afghanistan  on  02-09-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-10-2020
No cases found in Country/Region  Afghanistan  on  02-10-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-11-2020
No cases found in Country/Region  Afghanistan  on  02-11-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-12-2020
No cases found in Country/Region  Afghanistan  on  02-12-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-13-2020
No cases found in Country/Region  Afghanistan  on  02-13-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-14-2020
No cases found in Country/Region  Afghanistan  on  02-14-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-15-2020
No cases found in Country/Region  Afghanistan  on  02-15-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-16-2020
No cases found in Country/Region  Afghanistan  on  02-16-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-17-2020
No cases found in Country/Region  Afghanistan  on  02-17-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-18-2020
No cases found in Country/Region  Afghanistan  on  02-18-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-19-2020
No cases found in Country/Region  Afghanistan  on  02-19-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-20-2020
No cases found in Country/Region  Afghanistan  on  02-20-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-21-2020
No cases found in Country/Region  Afghanistan  on  02-21-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-22-2020
No cases found in Country/Region  Afghanistan  on  02-22-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-23-2020
No cases found in Country/Region  Afghanistan  on  02-23-2020
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-24-2020
Total number of confirmed cases in Country/Region Afghanistan  on  02-24-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  02-24-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  02-24-2020  was  0
delta confirmed is 1
delta deaths is 0
delta recovered is 0
delta active is 1
Frist case for Afghanistan on 02-24-2020
Afghanistan 02-25-2020
Total number of confirmed cases in Country/Region Afghanistan  on  02-25-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  02-25-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  02-25-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-26-2020
Total number of confirmed cases in Country/Region Afghanistan  on  02-26-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  02-26-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  02-26-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-27-2020
Total number of confirmed cases in Country/Region Afghanistan  on  02-27-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  02-27-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  02-27-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-28-2020
Total number of confirmed cases in Country/Region Afghanistan  on  02-28-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  02-28-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  02-28-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 02-29-2020
Total number of confirmed cases in Country/Region Afghanistan  on  02-29-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  02-29-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  02-29-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-01-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-01-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  03-01-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-01-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-02-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-02-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  03-02-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-02-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-03-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-03-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  03-03-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-03-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-04-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-04-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  03-04-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-04-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-05-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-05-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  03-05-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-05-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-06-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-06-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  03-06-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-06-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-07-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-07-2020  was  1
Total number of deaths in Country/Region Afghanistan  on  03-07-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-07-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-08-2020

/Users/vishalranjan/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: count is deprecated. Use Collection.count_documents instead.

/Users/vishalranjan/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: DeprecationWarning: update is deprecated. Use replace_one, update_one or update_many instead.
  # This is added back by InteractiveShellApp.init_path()

Total number of confirmed cases in Country/Region Afghanistan  on  03-08-2020  was  4
Total number of deaths in Country/Region Afghanistan  on  03-08-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-08-2020  was  0
delta confirmed is 3
delta deaths is 0
delta recovered is 0
delta active is 3
Afghanistan 03-09-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-09-2020  was  4
Total number of deaths in Country/Region Afghanistan  on  03-09-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-09-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-10-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-10-2020  was  5
Total number of deaths in Country/Region Afghanistan  on  03-10-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-10-2020  was  0
delta confirmed is 1
delta deaths is 0
delta recovered is 0
delta active is 1
Afghanistan 03-11-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-11-2020  was  7
Total number of deaths in Country/Region Afghanistan  on  03-11-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-11-2020  was  0
delta confirmed is 2
delta deaths is 0
delta recovered is 0
delta active is 2
Afghanistan 03-12-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-12-2020  was  7
Total number of deaths in Country/Region Afghanistan  on  03-12-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-12-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-13-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-13-2020  was  7
Total number of deaths in Country/Region Afghanistan  on  03-13-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-13-2020  was  0
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-14-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-14-2020  was  11
Total number of deaths in Country/Region Afghanistan  on  03-14-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-14-2020  was  0
delta confirmed is 4
delta deaths is 0
delta recovered is 0
delta active is 4
Afghanistan 03-15-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-15-2020  was  16
Total number of deaths in Country/Region Afghanistan  on  03-15-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-15-2020  was  0
delta confirmed is 5
delta deaths is 0
delta recovered is 0
delta active is 5
Afghanistan 03-16-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-16-2020  was  21
Total number of deaths in Country/Region Afghanistan  on  03-16-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-16-2020  was  1
delta confirmed is 5
delta deaths is 0
delta recovered is 1
delta active is 4
Afghanistan 03-17-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-17-2020  was  22
Total number of deaths in Country/Region Afghanistan  on  03-17-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-17-2020  was  1
delta confirmed is 1
delta deaths is 0
delta recovered is 0
delta active is 1
Afghanistan 03-18-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-18-2020  was  22
Total number of deaths in Country/Region Afghanistan  on  03-18-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-18-2020  was  1
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-19-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-19-2020  was  22
Total number of deaths in Country/Region Afghanistan  on  03-19-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-19-2020  was  1
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-20-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-20-2020  was  24
Total number of deaths in Country/Region Afghanistan  on  03-20-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-20-2020  was  1
delta confirmed is 2
delta deaths is 0
delta recovered is 0
delta active is 2
Afghanistan 03-21-2020
Total number of confirmed cases in Country/Region Afghanistan  on  03-21-2020  was  24
Total number of deaths in Country/Region Afghanistan  on  03-21-2020  was  0
Total number of recovered cases in Country/Region Afghanistan  on  03-21-2020  was  1
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-22-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-22-2020  was  40
Total number of deaths in Country_Region Afghanistan  on  03-22-2020  was  1
Total number of recovered cases in Country_Region Afghanistan  on  03-22-2020  was  1
delta confirmed is 16
delta deaths is 1
delta recovered is 0
delta active is 15
Afghanistan 03-23-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-23-2020  was  40
Total number of deaths in Country_Region Afghanistan  on  03-23-2020  was  1
Total number of recovered cases in Country_Region Afghanistan  on  03-23-2020  was  1
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-24-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-24-2020  was  74
Total number of deaths in Country_Region Afghanistan  on  03-24-2020  was  1
Total number of recovered cases in Country_Region Afghanistan  on  03-24-2020  was  1
delta confirmed is 34
delta deaths is 0
delta recovered is 0
delta active is 34
Afghanistan 03-25-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-25-2020  was  84
Total number of deaths in Country_Region Afghanistan  on  03-25-2020  was  2
Total number of recovered cases in Country_Region Afghanistan  on  03-25-2020  was  2
delta confirmed is 10
delta deaths is 1
delta recovered is 1
delta active is 8
Afghanistan 03-26-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-26-2020  was  94
Total number of deaths in Country_Region Afghanistan  on  03-26-2020  was  4
Total number of recovered cases in Country_Region Afghanistan  on  03-26-2020  was  2
delta confirmed is 10
delta deaths is 2
delta recovered is 0
delta active is 8
Afghanistan 03-27-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-27-2020  was  110
Total number of deaths in Country_Region Afghanistan  on  03-27-2020  was  4
Total number of recovered cases in Country_Region Afghanistan  on  03-27-2020  was  2
delta confirmed is 16
delta deaths is 0
delta recovered is 0
delta active is 16
Afghanistan 03-28-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-28-2020  was  110
Total number of deaths in Country_Region Afghanistan  on  03-28-2020  was  4
Total number of recovered cases in Country_Region Afghanistan  on  03-28-2020  was  2
delta confirmed is 0
delta deaths is 0
delta recovered is 0
delta active is 0
Afghanistan 03-29-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-29-2020  was  120
Total number of deaths in Country_Region Afghanistan  on  03-29-2020  was  4
Total number of recovered cases in Country_Region Afghanistan  on  03-29-2020  was  2
delta confirmed is 10
delta deaths is 0
delta recovered is 0
delta active is 10
Afghanistan 03-30-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-30-2020  was  170
Total number of deaths in Country_Region Afghanistan  on  03-30-2020  was  4
Total number of recovered cases in Country_Region Afghanistan  on  03-30-2020  was  2
delta confirmed is 50
delta deaths is 0
delta recovered is 0
delta active is 50
Afghanistan 03-31-2020
Total number of confirmed cases in Country_Region Afghanistan  on  03-31-2020  was  174
Total number of deaths in Country_Region Afghanistan  on  03-31-2020  was  4
Total number of recovered cases in Country_Region Afghanistan  on  03-31-2020  was  5
delta confirmed is 4
delta deaths is 0
delta recovered is 3
delta active is 1
Afghanistan 04-01-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-01-2020  was  237
Total number of deaths in Country_Region Afghanistan  on  04-01-2020  was  4
Total number of recovered cases in Country_Region Afghanistan  on  04-01-2020  was  5
delta confirmed is 63
delta deaths is 0
delta recovered is 0
delta active is 63
Afghanistan 04-02-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-02-2020  was  273
Total number of deaths in Country_Region Afghanistan  on  04-02-2020  was  6
Total number of recovered cases in Country_Region Afghanistan  on  04-02-2020  was  10
delta confirmed is 36
delta deaths is 2
delta recovered is 5
delta active is 29
Afghanistan 04-03-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-03-2020  was  281
Total number of deaths in Country_Region Afghanistan  on  04-03-2020  was  6
Total number of recovered cases in Country_Region Afghanistan  on  04-03-2020  was  10
delta confirmed is 8
delta deaths is 0
delta recovered is 0
delta active is 8
Afghanistan 04-04-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-04-2020  was  299
Total number of deaths in Country_Region Afghanistan  on  04-04-2020  was  7
Total number of recovered cases in Country_Region Afghanistan  on  04-04-2020  was  10
delta confirmed is 18
delta deaths is 1
delta recovered is 0
delta active is 17
Afghanistan 04-05-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-05-2020  was  349
Total number of deaths in Country_Region Afghanistan  on  04-05-2020  was  7
Total number of recovered cases in Country_Region Afghanistan  on  04-05-2020  was  15
delta confirmed is 50
delta deaths is 0
delta recovered is 5
delta active is 45
Afghanistan 04-06-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-06-2020  was  367
Total number of deaths in Country_Region Afghanistan  on  04-06-2020  was  11
Total number of recovered cases in Country_Region Afghanistan  on  04-06-2020  was  18
delta confirmed is 18
delta deaths is 4
delta recovered is 3
delta active is 11
Afghanistan 04-07-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-07-2020  was  423
Total number of deaths in Country_Region Afghanistan  on  04-07-2020  was  14
Total number of recovered cases in Country_Region Afghanistan  on  04-07-2020  was  18
delta confirmed is 56
delta deaths is 3
delta recovered is 0
delta active is 53
Afghanistan 04-08-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-08-2020  was  444
Total number of deaths in Country_Region Afghanistan  on  04-08-2020  was  14
Total number of recovered cases in Country_Region Afghanistan  on  04-08-2020  was  29
delta confirmed is 21
delta deaths is 0
delta recovered is 11
delta active is 10
Afghanistan 04-09-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-09-2020  was  484
Total number of deaths in Country_Region Afghanistan  on  04-09-2020  was  15
Total number of recovered cases in Country_Region Afghanistan  on  04-09-2020  was  32
delta confirmed is 40
delta deaths is 1
delta recovered is 3
delta active is 36
Afghanistan 04-10-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-10-2020  was  521
Total number of deaths in Country_Region Afghanistan  on  04-10-2020  was  15
Total number of recovered cases in Country_Region Afghanistan  on  04-10-2020  was  32
delta confirmed is 37
delta deaths is 0
delta recovered is 0
delta active is 37
Afghanistan 04-11-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-11-2020  was  555
Total number of deaths in Country_Region Afghanistan  on  04-11-2020  was  18
Total number of recovered cases in Country_Region Afghanistan  on  04-11-2020  was  32
delta confirmed is 34
delta deaths is 3
delta recovered is 0
delta active is 31
Afghanistan 04-12-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-12-2020  was  607
Total number of deaths in Country_Region Afghanistan  on  04-12-2020  was  18
Total number of recovered cases in Country_Region Afghanistan  on  04-12-2020  was  32
delta confirmed is 52
delta deaths is 0
delta recovered is 0
delta active is 52
Afghanistan 04-13-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-13-2020  was  665
Total number of deaths in Country_Region Afghanistan  on  04-13-2020  was  21
Total number of recovered cases in Country_Region Afghanistan  on  04-13-2020  was  32
delta confirmed is 58
delta deaths is 3
delta recovered is 0
delta active is 55
Afghanistan 04-14-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-14-2020  was  714
Total number of deaths in Country_Region Afghanistan  on  04-14-2020  was  23
Total number of recovered cases in Country_Region Afghanistan  on  04-14-2020  was  40
delta confirmed is 49
delta deaths is 2
delta recovered is 8
delta active is 39
Afghanistan 04-15-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-15-2020  was  784
Total number of deaths in Country_Region Afghanistan  on  04-15-2020  was  25
Total number of recovered cases in Country_Region Afghanistan  on  04-15-2020  was  43
delta confirmed is 70
delta deaths is 2
delta recovered is 3
delta active is 65
Afghanistan 04-16-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-16-2020  was  840
Total number of deaths in Country_Region Afghanistan  on  04-16-2020  was  30
Total number of recovered cases in Country_Region Afghanistan  on  04-16-2020  was  54
delta confirmed is 56
delta deaths is 5
delta recovered is 11
delta active is 40
Afghanistan 04-17-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-17-2020  was  906
Total number of deaths in Country_Region Afghanistan  on  04-17-2020  was  30
Total number of recovered cases in Country_Region Afghanistan  on  04-17-2020  was  99
delta confirmed is 66
delta deaths is 0
delta recovered is 45
delta active is 21
Afghanistan 04-18-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-18-2020  was  933
Total number of deaths in Country_Region Afghanistan  on  04-18-2020  was  30
Total number of recovered cases in Country_Region Afghanistan  on  04-18-2020  was  112
delta confirmed is 27
delta deaths is 0
delta recovered is 13
delta active is 14
Afghanistan 04-19-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-19-2020  was  996
Total number of deaths in Country_Region Afghanistan  on  04-19-2020  was  33
Total number of recovered cases in Country_Region Afghanistan  on  04-19-2020  was  131
delta confirmed is 63
delta deaths is 3
delta recovered is 19
delta active is 41
Afghanistan 04-20-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-20-2020  was  1026
Total number of deaths in Country_Region Afghanistan  on  04-20-2020  was  36
Total number of recovered cases in Country_Region Afghanistan  on  04-20-2020  was  135
delta confirmed is 30
delta deaths is 3
delta recovered is 4
delta active is 23
Afghanistan 04-21-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-21-2020  was  1092
Total number of deaths in Country_Region Afghanistan  on  04-21-2020  was  36
Total number of recovered cases in Country_Region Afghanistan  on  04-21-2020  was  150
delta confirmed is 66
delta deaths is 0
delta recovered is 15
delta active is 51
Afghanistan 04-22-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-22-2020  was  1176
Total number of deaths in Country_Region Afghanistan  on  04-22-2020  was  40
Total number of recovered cases in Country_Region Afghanistan  on  04-22-2020  was  166
delta confirmed is 84
delta deaths is 4
delta recovered is 16
delta active is 64
Afghanistan 04-23-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-23-2020  was  1279
Total number of deaths in Country_Region Afghanistan  on  04-23-2020  was  42
Total number of recovered cases in Country_Region Afghanistan  on  04-23-2020  was  179
delta confirmed is 103
delta deaths is 2
delta recovered is 13
delta active is 88
Afghanistan 04-24-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-24-2020  was  1351
Total number of deaths in Country_Region Afghanistan  on  04-24-2020  was  43
Total number of recovered cases in Country_Region Afghanistan  on  04-24-2020  was  188
delta confirmed is 72
delta deaths is 1
delta recovered is 9
delta active is 62
Afghanistan 04-25-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-25-2020  was  1463
Total number of deaths in Country_Region Afghanistan  on  04-25-2020  was  47
Total number of recovered cases in Country_Region Afghanistan  on  04-25-2020  was  188
delta confirmed is 112
delta deaths is 4
delta recovered is 0
delta active is 108
Afghanistan 04-26-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-26-2020  was  1531
Total number of deaths in Country_Region Afghanistan  on  04-26-2020  was  50
Total number of recovered cases in Country_Region Afghanistan  on  04-26-2020  was  207
delta confirmed is 68
delta deaths is 3
delta recovered is 19
delta active is 46
Afghanistan 04-27-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-27-2020  was  1703
Total number of deaths in Country_Region Afghanistan  on  04-27-2020  was  57
Total number of recovered cases in Country_Region Afghanistan  on  04-27-2020  was  220
delta confirmed is 172
delta deaths is 7
delta recovered is 13
delta active is 152
Afghanistan 04-28-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-28-2020  was  1828
Total number of deaths in Country_Region Afghanistan  on  04-28-2020  was  58
Total number of recovered cases in Country_Region Afghanistan  on  04-28-2020  was  228
delta confirmed is 125
delta deaths is 1
delta recovered is 8
delta active is 116
Afghanistan 04-29-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-29-2020  was  1939
Total number of deaths in Country_Region Afghanistan  on  04-29-2020  was  60
Total number of recovered cases in Country_Region Afghanistan  on  04-29-2020  was  252
delta confirmed is 111
delta deaths is 2
delta recovered is 24
delta active is 85
Afghanistan 04-30-2020
Total number of confirmed cases in Country_Region Afghanistan  on  04-30-2020  was  2171
Total number of deaths in Country_Region Afghanistan  on  04-30-2020  was  64
Total number of recovered cases in Country_Region Afghanistan  on  04-30-2020  was  260
delta confirmed is 232
delta deaths is 4
delta recovered is 8
delta active is 220
Afghanistan 05-01-2020
Total number of confirmed cases in Country_Region Afghanistan  on  05-01-2020  was  2335
Total number of deaths in Country_Region Afghanistan  on  05-01-2020  was  68
Total number of recovered cases in Country_Region Afghanistan  on  05-01-2020  was  310
delta confirmed is 164
delta deaths is 4
delta recovered is 50
delta active is 110
Afghanistan 05-02-2020
Total number of confirmed cases in Country_Region Afghanistan  on  05-02-2020  was  2469
Total number of deaths in Country_Region Afghanistan  on  05-02-2020  was  72
Total number of recovered cases in Country_Region Afghanistan  on  05-02-2020  was  331
delta confirmed is 134
delta deaths is 4
delta recovered is 21
delta active is 109
Afghanistan 05-03-2020
Total number of confirmed cases in Country_Region Afghanistan  on  05-03-2020  was  2704

FileNotFoundError: [Errno 2] File data/05-13-2020.csv does not exist: 'data/05-13-2020.csv'

# Adding Time series data for World

## Getting daily data for world

In [ ]:
def get_daily_data_for_world(df, valid_date, first_case_found):
    confirmed_cases_count = df['Confirmed'].sum()
    death_cases_count = df['Deaths'].sum()
    recovered_cases_count = df['Recovered'].sum()
    active_cases_count = confirmed_cases_count - (recovered_cases_count + death_cases_count)
    print(confirmed_cases_count)
    print('on ', valid_date, ' the cases are ', confirmed_cases_count)
    world_minimum_confirmed = df['Confirmed'].min()
    world_minimum_deaths = df['Deaths'].min()
    world_minimum_recovered = df['Recovered'].min()
    
    world_maximum_confirmed = df['Confirmed'].max()
    world_maximum_deaths = df['Deaths'].max()
    world_maximum_recovered = df['Recovered'].max()
    
    return confirmed_cases_count, death_cases_count, recovered_cases_count, active_cases_count, world_minimum_confirmed, world_minimum_deaths, world_minimum_recovered, world_maximum_confirmed, world_maximum_deaths, world_maximum_recovered, valid_date

## Saving daily data for world

In [ ]:
def add_data_for_world_to_db(date, total_confirmed, delta_confirmed, total_deaths, delta_deaths, total_recovered, delta_recovered, total_active, delta_active, world_minimum_confirmed, world_minimum_deaths, world_minimum_recovered, world_maximum_confirmed, world_maximum_deaths, world_maximum_recovered):
    if countries_collection.find({'name': 'world'}).count() >0:
        time_series = []
        date_obj = {
            "date": str(date_of_first_incident),
            "confirmed": {"count": total_confirmed, "delta": delta_confirmed },
            "deaths": {"count": total_deaths, "delta": delta_deaths},
            "recovered": {"count": total_recovered, "delta": delta_recovered},
            "active": {"count":total_active, "delta": delta_active},
            "meta": {
                "confirmed": {
                    "min": world_minimum_confirmed,
                    "max": world_maximum_confirmed
                },
                "deaths": {
                    "min": world_minimum_deaths,
                    "max": world_maximum_deaths
                },
                "recovered": {
                    "min": world_minimum_recovered,
                    "max": world_maximum_recovered
                },
            }
        }
        countries_collection.update({'name': 'world'}, {'$push': {'timesSeries': date_obj}}) 
    else:
        time_series = []
        date_obj = [{
        "date": str(date_of_first_incident),
        "confirmed": {"count": total_confirmed, "delta": delta_confirmed },
        "deaths": {"count": total_deaths, "delta": delta_deaths},
        "recovered": {"count": total_recovered, "delta": delta_recovered},
        "active": {"count":total_active, "delta": delta_active},
        }]
        #time_series.append[date_obj]
        datax =  {
            "name": 'world',
            "coordinates":
            {
                "lat": '0',
                "long": '0'
            },
            "firstIncidentDate": date_of_first_incident,
            "timesSeries":date_obj,
            "lastUpdatedAt": "04-25-2020",
            "province": "NA"

        }
        print(datax)
        x = countries_collection.insert_one(datax)

## Iterating daily files for world

In [ ]:
days_since_first_data = (today-first_available_data_date).days
date_iterator = first_available_data_date
first_case_found = False
previous_confirmed_count = 0;
previous_deaths_count = 0;
previous_recovered_count = 0;
previous_active_count = 0;
for day in range(days_since_first_data):
    date_iterator_month = str(date_iterator.month) if len(str(date_iterator.month)) > 1 else '0'+str(date_iterator.month)
    date_iterator_day = str(date_iterator.day) if len(str(date_iterator.day)) > 1 else '0'+str(date_iterator.day)
    date_iterator_year = str(date_iterator.year)
    valid_date = date_iterator_month + '-' + date_iterator_day + '-' + date_iterator_year
    valid_file_name = date_iterator_month + '-' + date_iterator_day + '-' + date_iterator_year +'.csv'
    print(valid_date)

    #print(day," st day valid date is:",valid_file_name)
    df = pd.read_csv('data/'+valid_file_name)
    df.fillna(0, axis=1,inplace=True)

    total_confirmed, total_deaths, total_recovered, total_active, world_minimum_confirmed, world_minimum_deaths, world_minimum_recovered, world_maximum_confirmed, world_maximum_deaths, world_maximum_recovered, date_of_first_incident = get_daily_data_for_world(df,valid_date,first_case_found)
    delta_confirmed = total_confirmed - previous_confirmed_count
    delta_deaths = total_deaths - previous_deaths_count
    delta_recovered = total_recovered - previous_recovered_count
    delta_active = total_active - previous_active_count
    print('delta confirmed is', delta_confirmed)
    print('delta deaths is', delta_deaths)
    print('delta recovered is', delta_recovered)
    print('delta active is', delta_active)
    previous_confirmed_count = total_confirmed
    previous_deaths_count = total_deaths
    previous_recovered_count = total_recovered
    previous_active_count = total_active

    if total_confirmed > 0:
        if first_case_found == False:
            print('Frist case for world'  'on' , date_of_first_incident )
            add_data_for_world_to_db(date_of_first_incident, int(total_confirmed), int(delta_confirmed), total_deaths=0, delta_deaths=0, total_recovered=0, delta_recovered=0, total_active=0, delta_active=0,world_minimum_confirmed=0, world_minimum_deaths=0, world_minimum_recovered=0, world_maximum_confirmed=0, world_maximum_deaths=0, world_maximum_recovered=0)
            first_case_found = True
        else:
            add_data_for_world_to_db(valid_date, int(total_confirmed), int(delta_confirmed), int(total_deaths), int(delta_deaths), int(total_recovered), int(delta_recovered),int(total_active), int(delta_active), world_minimum_confirmed, world_minimum_deaths, world_minimum_recovered, world_maximum_confirmed, world_maximum_deaths, world_maximum_recovered)
    date_iterator = date_iterator + datetime.timedelta(days=1)

In [ ]:
pwd

In [ ]:
df_latest = pd.read_csv('data/05-07-2020.csv')

In [ ]:
df_latest.head()

In [ ]:
us_data = df_latest[df['Country_Region']=='Italy']

In [ ]:
us_data['Confirmed'].sum()

In [ ]:
us_data['Deaths'].sum()

In [ ]:
type(int(df_latest['Confirmed'].sum()))

In [ ]:
df_latest['Deaths'].sum()

In [ ]:
df_latest['Deaths'].sum()

In [ ]:
import seaborn as sns

In [ ]:
sns.palplot(sns.color_palette("Blues",4))

In [ ]:
sns.palplot(sns.color_palette("Greens",4))

In [ ]:
sns.palplot(sns.color_palette("Oranges",4))
# orange: #FC6600
# Royal : #F9812A
# Gold: #F9A602
# Amber: #FFBF00

In [ ]:
sns.palplot(sns.color_palette("Reds",4))

In [ ]:
# orange: #FC6600
# Royal : #F9812A
# Gold: #F9A602
# Amber: #FFBF00



# 1----BLUE 
# #4-----#1764ab
# #3-----#4a97c9
# #2-----#93c4de
# #1-----#cfe1f2


# 2.---GREENS
# #4---#157e3a
# #3---#4bb061
# #2---#98d493
# #1---#d3edcc

# 3----Oranges
# orange: #FC6600
# Royal : #F9812A
# Gold: #F9A602
# Amber: #FFBF00

# 4-----REDS
# #4-----#bb141a
# #3-----#f14431
# #2-----#fb8a6a
# #1-----#fcc9b4